server:
  port: 4321
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8

knife4j:
  enable: true
  setting:
    enableFooter: false
    enableOpenApi: false
    enableGroup: false
    swaggerModelName: 自定义类型
  cors: true
  production: true

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/vue_back?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 3000
      max-lifetime: 1800000
      idle-timeout: 600000
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
        max-wait: -1
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 127.0.0.1:9300

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

system:
  config:
    # 登录超时时间,单位: 毫秒
    loginTimeOut: 1800000
    # 初始化SQL脚本
    sqlFilepath: classpath:sql/vue_back.sql
    # 登录互踢模式： true-是,false-否
    kickMode: true