server:
  port: 4321
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB